(() => {
  const DEFAULTS = { enabled:true, mode:'blackout', blockedChannels:[], customImage:'' };
  let settings = { ...DEFAULTS };
  let scheduled = false;
  const CARD_SELECTORS = ['ytd-rich-item-renderer','ytd-video-renderer','ytd-grid-video-renderer','ytd-compact-video-renderer','ytd-playlist-video-renderer','ytd-reel-item-renderer','ytm-shorts-lockup-view-model','ytd-rich-grid-media','ytd-post-renderer','ytd-backstage-post-thread-renderer','ytd-backstage-post-renderer'];
  const CHANNEL_LINK_SELECTOR = ['a[href^="/@"]','a[href^="/channel/"]','a[href^="/c/"]','a[href^="/user/"]'].join(',');
  function normalizeKey(value){ if(!value)return''; try{const url=new URL(value,location.origin);const p=url.pathname.replace(/\/$/,'');if(p.startsWith('/@')||p.startsWith('/channel/')||p.startsWith('/c/')||p.startsWith('/user/'))return p.toLowerCase();return'';}catch{return String(value).trim().toLowerCase();}}
  function labelFor(card){const tag=card.tagName.toLowerCase();return tag.includes('post')||card.querySelector('ytd-backstage-post-renderer')?'차단된 채널의 게시물':(tag.includes('reel')||tag.includes('shorts'))?'차단된 채널의 Shorts':'차단된 채널의 콘텐츠';}
  function findChannelKey(card){const links=[...card.querySelectorAll(CHANNEL_LINK_SELECTOR)];const preferred=links.find(a=>/channel-name|author|byline|owner|avatar/i.test(a.id+' '+a.className));const candidate=preferred||links[0];return candidate?normalizeKey(candidate.getAttribute('href')):'';}
  function isBlocked(key){return !!key&&settings.blockedChannels.some(item=>normalizeKey(item.key||item)===key);}
  function applyMode(card){card.classList.remove('bfy-hidden','bfy-censored','bfy-blur','bfy-image');card.style.removeProperty('--bfy-custom-image');if(settings.mode==='hide'){card.classList.add('bfy-hidden');return;}card.classList.add('bfy-censored');card.dataset.bfyLabel=labelFor(card);if(settings.mode==='blur')card.classList.add('bfy-blur');else if(settings.mode==='image'&&settings.customImage){card.classList.add('bfy-image');const safe=settings.customImage.replace(/"/g,'%22');card.style.setProperty('--bfy-custom-image',`url("${safe}")`);}}
  function restore(card){card.classList.remove('bfy-hidden','bfy-censored','bfy-blur','bfy-image');card.style.removeProperty('--bfy-custom-image');delete card.dataset.bfyLabel;}
  function addBlockButton(card,key){if(!key||card.querySelector(':scope > .bfy-block-button'))return;card.classList.add('bfy-card');const btn=document.createElement('button');btn.className='bfy-block-button';btn.type='button';btn.textContent='차단';btn.title='이 채널을 Blackout 목록에 추가';btn.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();const existing=settings.blockedChannels.filter(x=>normalizeKey(x.key||x)!==key);existing.push({key,addedAt:new Date().toISOString()});settings.blockedChannels=existing;await chrome.storage.local.set({blockedChannels:existing});scan();},true);card.appendChild(btn);}
  function processCard(card){if(!(card instanceof HTMLElement))return;const key=findChannelKey(card);if(!key)return;addBlockButton(card,key);if(settings.enabled&&isBlocked(key)){const btn=card.querySelector(':scope > .bfy-block-button');if(btn)btn.remove();applyMode(card);}else restore(card);}
  function scan(root=document){if(!settings.enabled)document.querySelectorAll('.bfy-censored,.bfy-hidden').forEach(restore);for(const selector of CARD_SELECTORS){root.querySelectorAll?.(selector).forEach(processCard);if(root.matches?.(selector))processCard(root);}}
  function queueScan(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;scan();});}
  async function loadSettings(){const saved=await chrome.storage.local.get(DEFAULTS);settings={...DEFAULTS,...saved};scan();}
  chrome.storage.onChanged.addListener((changes,area)=>{if(area!=='local')return;for(const[key,{newValue}]of Object.entries(changes))settings[key]=newValue;queueScan();});
  const observer=new MutationObserver(queueScan);observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('yt-navigate-finish',queueScan,true);loadSettings();
})();
